### ISSUE TITLE
probeSniffer crashes on my device

### ISSUE THREAD

**Issue by ghost** [xdavidhu/probeSniffer#15]
Hello!

I've installed all the requirements, followed every required step but when I launch the script and come close to it with an iPhone there are some errors showing up. In the image below you can see them. I don't know how to solve this as I'm not familiar with Python.

![screenshot](https://user-images.githubusercontent.com/28964694/35481104-3ea38e66-041d-11e8-9aa5-afa169f58e77.png)

Thanks for the answer and the script!
Regards

**Comment by xdavidhu** [comment]
Hey!

Is the interface in monitor mode?
If not, you can use airmon-ng to set it like this:
`sudo airmon-ng start [INTERFACE]`

**Comment by ghost** [comment]
I can confirm. I’ve set the interface in monitor mode before running your script.

**Comment by xdavidhu** [comment]
Okey so this was a weird and super annoying bug.. On Kali there is no "wlan_mgt" layer on the packets, but 2 "wlan" layer.

Managed to fix the issue in 4699aa8bf3e1aa6e527897da9a91f47b465292bf
Please try it and let me know if it worked.

Thanks for reporting the bug!

**Comment by ghost** [comment]
Thanks! That fixed it!

**Comment by TheReal1604** [comment]
@xdavidhu got a similar error, unfortunatly its also crashing with your fix.
```
!] An error occurred. Debug:
Traceback (most recent call last):
  File "./probeSniffer.py.1", line 395, in main
    capture.apply_on_packets(packetHandler)
  File "/usr/local/lib/python3.6/dist-packages/pyshark-0.3.7.11-py3.6.egg/pyshark/capture/capture.py", line 248, in apply_on_packets
    return self.eventloop.run_until_complete(coro)
  File "/usr/local/lib/python3.6/dist-packages/trollius-1.0.4-py3.6.egg/trollius/base_events.py", line 300, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/trollius-1.0.4-py3.6.egg/trollius/futures.py", line 287, in result
    raise self._exception
  File "/usr/local/lib/python3.6/dist-packages/trollius-1.0.4-py3.6.egg/trollius/tasks.py", line 255, in _step
    result = next(coro)
  File "/usr/local/lib/python3.6/dist-packages/pyshark-0.3.7.11-py3.6.egg/pyshark/capture/capture.py", line 261, in packets_from_tshark
    packet_count=packet_count))
  File "/usr/local/lib/python3.6/dist-packages/trollius-1.0.4-py3.6.egg/trollius/tasks.py", line 253, in _step
    result = coro.send(value)
  File "/usr/local/lib/python3.6/dist-packages/pyshark-0.3.7.11-py3.6.egg/pyshark/capture/capture.py", line 290, in _go_through_packets_from_fd
    packet_callback(packet)
  File "./probeSniffer.py.1", line 194, in packetHandler
    ssid = pkt[3].ssid
  File "/usr/local/lib/python3.6/dist-packages/pyshark-0.3.7.11-py3.6.egg/pyshark/packet/layer.py", line 36, in __getattr__
    raise AttributeError()
AttributeError
```
Also running this on a kali linux system. Any ideas? :)
